name: Omnix Infra Updater

on:
  repository_dispatch:
    types: [update]

jobs:
  updater:
    name: Update Image Version
    runs-on: ubuntu-latest
    steps:
     - 
      name: Get Params 
      env:
        SEARCH: ${{ github.event.client_payload.search }}
        NEW_VERSION: ${{ github.event.client_payload.newVersion }}
      run: |
        bash ./updater.sh $SEARCH $NEW_VERSION
        cat ./example.yaml


