name: Omnix Infra Updater

on:
  repository_dispatch:
    types: [update]

env:
  SEARCH: ${{ github.event.client_payload.search }}
  NEW_VERSION: ${{ github.event.client_payload.newVersion }}

jobs:
  updater:
    name: Update Image Version
    runs-on: ubuntu-latest
    steps:
     - 
        name: Checkout
        uses: actions/checkout@v2
     - 
      name: Replace version
      run: |
        bash ./updater.sh $SEARCH $NEW_VERSION
        cat ./example.yaml
     - 
      name: Commit changes
      run: |
          git config --global user.name 'Brandonslp'
          git config --global user.email 'brandonslp.bl@gmail.com'
          git commit -am "Automated update: $SEARCH to $NEW_VERSION"
          git push


